name: cpp-linter

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  cpp-linter:
    uses: cda-tum/mqt-core/.github/workflows/reusable-cpp-linter.yml@make-reusable-workflows-more-generic
    with:
      cmake-args: -DBUILD_QMAP_TESTS=ON
      setup-z3: true
      z3-version: 4.11.2
