name: Python

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  min-qiskit-version:
    name: ⚛️ Min. Qiskit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Install Z3
        uses: cda-tum/setup-z3@v1
        with:
          version: 4.11.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup nox
        run: pipx install nox
      - name: Run session
        run: nox -s min_qiskit_version -- --cov-report=xml
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          fail_ci_if_error: true
          flags: python
          token: ${{ secrets.CODECOV_TOKEN }}
